# Generated by Django 3.2.12 on 2025-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_auto_20250115_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinput',
            name='emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
