# Generated by Django 3.2.12 on 2025-01-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_dailyinput_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyinput',
            name='sentiment',
        ),
    ]
