# Generated by Django 3.2.12 on 2025-01-15 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_remove_dailyinput_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='doctor_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
