# Generated by Django 2.2 on 2019-04-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile_number', models.TextField()),
            ],
        ),
    ]
