# Generated by Django 2.2 on 2019-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile_number', models.TextField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='mobile_number',
            field=models.TextField(max_length=10),
        ),
    ]
