# Generated by Django 2.2 on 2019-04-12 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
